sudo: false

language: python
python:
  - 2.7
  - 3.6

matrix:
  allow_failures:
    - python: 3.7-dev

addons:
  apt:
    packages:
      - python-gi
      - gir1.2-webkit-3.0
      
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

install:
  - pip install pytest

script:
  - python -m pytest tests


notifications:
  email: false
