sudo: false

language: python
python:
  - 2.7
  - 3.6

matrix:
  allow_failures:
    - python: 3.7-dev

addons:
  apt:
    packages:
      - python-gi
      - gir1.2-webkit-3.0


install:
  - pip install PyGObject pytest

script:
  - pytest tests


notifications:
  email: true
